export const LOGIN_PROGRESS = 'LOGIN_PROGRESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const USERCHECK_PROGRESS = 'USERCHECK_PROGRESS';
export const USERCHECK_SUCCESS = 'USERCHECK_SUCCESS';
export const USERCHECK_FAIL = 'USERCHECK_FAIL';

export const GETTRANSACTION_PROGRESS = 'GETTRANSACTION_PROGRESS';
export const GETTRANSACTION_SUCCESS = 'GETTRANSACTION_SUCCESS';
export const GETTRANSACTION_FAIL = 'GETTRANSACTION_FAIL';

export const HANDALBUY_PROGRESS = 'HANDALBUY_PROGRESS';
export const HANDALBUY_SUCCESS = 'HANDALBUY_SUCCESS';
export const HANDALBUY_FAIL = 'HANDALBUY_FAIL';

export const HANDALSELL_PROGRESS = 'HANDALSELL_PROGRESS';
export const HANDALSELL_SUCCESS = 'HANDALSELL_SUCCESS';
export const HANDALSELL_FAIL = 'HANDALSELL_FAIL';

export const GETRET_PROGRESS = 'GETRET_PROGRESS';
export const GETRET_SUCCESS = 'GETRET_SUCCESS';
export const GETRET_FAIL = 'GETRET_FAIL';

export const GETRECEIPT_PROGRESS = 'GETRECEIPT_PROGRESS';
export const GETRECEIPT_SUCCESS = 'GETRECEIPT_SUCCESS';
export const GETRECEIPT_FAIL = 'GETRECEIPT_FAIL';

export const APPLYPROMOCODE_PROGRESS = 'APPLYPROMOCODE_PROGRESS';
export const APPLYPROMOCODE_SUCCESS = 'APPLYPROMOCODE_SUCCESS';
export const APPLYPROMOCODE_FAIL = 'APPLYPROMOCODE_FAIL';

export const REMOVEPROMOCODE_PROGRESS = 'REMOVEPROMOCODE_PROGRESS';
export const REMOVEPROMOCODE_SUCCESS = 'REMOVEPROMOCODE_SUCCESS';
export const REMOVEPROMOCODE_FAIL = 'REMOVEPROMOCODE_FAIL';

export const APPLYVOUCHER_PROGRESS = 'APPLYVOUCHER_PROGRESS';
export const APPLYVOUCHER_SUCCESS = 'APPLYVOUCHER_SUCCESS';
export const APPLYVOUCHER_FAIL = 'APPLYVOUCHER_FAIL';

export const SELLGETRET_PROGRESS = 'SELLGETRET_PROGRESS';
export const SELLGETRET_SUCCESS = 'SELLGETRET_SUCCESS';
export const SELLGETRET_FAIL = 'SELLGETRET_FAIL';

export const CUSTOMEROTP_PROGRESS = 'CUSTOMEROTP_PROGRESS';
export const CUSTOMEROTP_SUCCESS = 'CUSTOMEROTP_SUCCESS';
export const CUSTOMEROTP_FAIL = 'CUSTOMEROTP_FAIL';

export const VERIFYOTP_PROGRESS = 'VERIFYOTP_PROGRESS';
export const VERIFYOTP_SUCCESS = 'VERIFYOTP_SUCCESS';
export const VERIFYOTP_FAIL = 'VERIFYOTP_FAIL';

export const SENDEMAILOTP_PROGRESS = 'SENDEMAILOTP_PROGRESS';
export const SENDEMAILOTP_SUCCESS = 'SENDEMAILOTP_SUCESS';
export const SENDEMAILOTP_FAIL = 'SENDEMAILOTP_FAIL';

export const GETPROOFLIST_PROGRESS = 'GETPROOFLIST_PROGRESS';
export const GETPROOFLIST_SUCCESS = 'GETPROOFLIST_SUCESS';
export const GETPROOFLIST_FAIL = 'GETPROOFLIST_FAIL';

export const GETSTATELIST_PROGRESS = 'GETSTATELIST_PROGRESS';
export const GETSTATELIST_SUCCESS = 'GETSTATELIST_SUCESS';
export const GETSTATELIST_FAIL = 'GETSTATELIST_FAIL';

export const GETCITYLIST_PROGRESS = 'GETCITYLIST_PROGRESS';
export const GETCITYLIST_SUCCESS = 'GETCITYLIST_SUCESS';
export const GETCITYLIST_FAIL = 'GETCITYLIST_FAIL';

export const VERIFYEMAILOTP_PROGRESS = 'VERIFYEMAILOTP_PROGRESS';
export const VERIFYEMAILOTP_SUCCESS = 'VERIFYEMAILOTP_SUCCESS';
export const VERIFYEMAILOTP_FAIL = 'VERIFYEMAILOTP_FAIL';

export const GETCOMPANYLIST_PROGRESS = 'GETCOMPANYLIST_PROGRESS';
export const GETCOMPANYLIST_SUCCESS = 'GETCOMPANYLIST_SUCESS';
export const GETCOMPANYLIST_FAIL = 'GETCOMPANYLIST_FAIL';

export const GETOTPFOREMAIL_PROGRESS = 'GETOTPFOREMAIL_PROGRESS';
export const GETOTPFOREMAIL_SUCCESS = 'GETOTPFOREMAIL_SUCESS';
export const GETOTPFOREMAIL_FAIL = 'GETOTPFOREMAIL_FAIL';

export const GETRELEATIONLIST_PROGRESS = 'GETRELEATIONLIST_PROGRESS';
export const GETRELEATIONLIST_SUCCESS = 'GETRELEATIONLIST_SUCESS';
export const GETRELEATIONLIST_FAIL = 'GETRELEATIONLIST_FAIL';

export const VERIFYREF_PROGRESS = 'VERIFYREF_PROGRESS';
export const VERIFYREF_SUCCESS = 'VERIFYREF_SUCESS';
export const VERIFYREF_FAIL = 'VERIFYREF_FAIL';

export const CREATECUSTOMER_PROGRESS = 'CREATECUSTOMER_PROGRESS';
export const CREATECUSTOMER_SUCCESS = 'CREATECUSTOMER_SUCESS';
export const CREATECUSTOMER_FAIL = 'CREATECUSTOMER_FAIL';

export const SAVEKYCDATA_SUCCESS = 'SAVEKYCDATA_SUCCESS';
export const SAVEOTHERDATA_SUCCESS = 'SAVEOTHERDATA_SUCCESS';
export const SAVENOMINEEDATA_SUCCESS = 'SAVENOMINEEDATA_SUCCESS';

export const FORGOTPIN_PROGRESS = 'FORGOTPIN_PROGRESS';
export const FORGOTPIN_SUCCESS = 'FORGOTPIN_SUCCESS';
export const FORGOTPIN_FAIL = 'FORGOTPIN_FAIL';

export const VERIFYOTPFORGOTPASS_PROGRESS = 'VERIFYOTPFORGOTPASS_PROGRESS';
export const VERIFYOTPFORGOTPASS_SUCCESS = 'VERIFYOTPFORGOTPASS_SUCCESS';
export const VERIFYOTPFORGOTPASS_FAIL = 'VERIFYOTPFORGOTPASS_FAIL';

export const KYCTYPE_PROGRESS = 'KYCTYPE_PROGRESS';
export const KYCTYPE_SUCCESS = 'KYCTYPE_SUCCESS';
export const KYCTYPE_FAIL = 'KYCTYPE_FAIL';

export const VERIFYKYC_PROGRESS = 'VERIFYKYC_PROGRESS';
export const VERIFYKYC_SUCCESS = 'VERIFYKYC_SUCCESS';
export const VERIFYKYC_FAIL = 'VERIFYKYC_FAIL';

export const RESETPIN_PROGRESS = 'RESETPIN_PROGRESS';
export const RESETPIN_SUCESS = 'RESETPIN_SUCESS';
export const RESETPIN_FAIL = 'RESETPIN_FAIL';

export const DASHBOARD_INFO_PROGRESS = 'DASHBOARD_INFO_PROGRESS';
export const DASHBOARD_INFO_SUCCESS = 'DASHBOARD_INFO_SUCCESS';
export const DASHBOARD_INFO_FAIL = 'DASHBOARD_INFO_FAIL';

export const APP_VERSION_PROGRESS = 'APP_VERSION_PROGRESS';
export const APP_VERSION_SUCCESS = 'APP_VERSION_SUCCESS';
export const APP_VERSION_FAIL = 'APP_VERSION_FAIL';


export const LANGUAGELIST_PROGRESS = 'LANGUAGELIST_PROGRESS';
export const LANGUAGELIST_SUCCESS = 'LANGUAGELIST_SUCCESS';
export const LANGUAGELIST_FAIL = 'LANGUAGELIST_FAIL';

export const LANGUAGEJSON_PROGRESS = 'LANGUAGEJSON_PROGRESS';
export const LANGUAGEJSON_SUCCESS = 'LANGUAGEJSON_SUCCESS';
export const LANGUAGEJSON_FAIL = 'LANGUAGEJSON_FAIL';

export const SETPIN_PROGRESS = 'SETPIN_PROGRESS';
export const SETPIN_SUCCESS = 'SETPIN_SUCCESS';
export const SETPIN_FAIL = 'SETPIN_FAIL';
















